
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INT fd forward program : command  program : program command  command : forward INT \n                    | fd INT  length : INT '
    
_lr_action_items = {'forward':([0,1,2,5,6,7,],[3,3,-1,-2,-3,-4,]),'fd':([0,1,2,5,6,7,],[4,4,-1,-2,-3,-4,]),'$end':([1,2,5,6,7,],[0,-1,-2,-3,-4,]),'INT':([3,4,],[6,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'command':([0,1,],[2,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> command','program',1,'p_program0','Parser.py',64),
  ('program -> program command','program',2,'p_program1','Parser.py',69),
  ('command -> forward INT','command',2,'p_command0','Parser.py',75),
  ('command -> fd INT','command',2,'p_command0','Parser.py',76),
  ('length -> INT','length',1,'p_length','Parser.py',80),
]
